name: walletapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  flutter:

    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_sizer: ^1.0.5
  google_fonts: ^5.1.0
  google_nav_bar: ^5.0.6
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  sizer_pro: ^2.1.0
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - image/ 
    - image/Level badge.png
